[project]
name = 'Blockchain-Based-Construction-Project-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.material-verification]
path = 'contracts/material-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.project-specification]
path = 'contracts/project-specification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
